/*
 * QEMU RISC-V Boot Helper
 *
 * Copyright (c) 2017 SiFive, Inc.
 * Copyright (c) 2019 Alistair Francis <alistair.francis@wdc.com>
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2 or later, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef RISCV_BOOT_H
#define RISCV_BOOT_H

void riscv_find_and_load_firmware(MachineState *machine,
                                  const char *default_machine_firmware,
                                  hwaddr firmware_load_addr);
target_ulong riscv_load_firmware(const char *firmware_filename,
                                 hwaddr firmware_load_addr);
target_ulong riscv_load_kernel(const char *kernel_filename);
hwaddr riscv_load_initrd(const char *filename, uint64_t mem_size,
                         uint64_t kernel_entry, hwaddr *start);

/**
 * riscv_load_fdt() - load a device tree binary image into memory
 * @fdt:        the address to load the image at
 * @addr_base:  expected dtb base address
 * @addr_limit: expected dtb binary boundary address
 * @as:         address space to load image to
 *
 * Load a device tree binary to specific address @addr_base. If it -dtb, use it.
 * or use default one, generated by each target board.
 *
 * If @addr_limit contains a meaningful value (i.e., it is strictly greater
 * than @addr), the device tree is only loaded if its size does not exceed
 * the limit.
 *
 * If "dumpdtb" machine option is set, dump the content and exit
 *
 * Returns: the size of the device tree image on success,
 *          -1 on errors.
 */
int riscv_load_fdt(void *fdt, hwaddr addr_base, hwaddr addr_limit,
                   AddressSpace *as);
#endif /* RISCV_BOOT_H */
